mainapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('roomapp.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roomapp/models.py
from django.db import models
import random
import string
from datetime import date, timedelta
from django.db.models import Sum
import nepali_datetime

# Utility functions
def random_string_generator(size=6, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def random_user_generator(size=3, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

class Customer(models.Model):
    # Fields remain unchanged
    full_name = models.CharField(max_length=255, blank=False)
    organization = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    designation = models.CharField(max_length=255, blank=True)
    passport_id_number = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    phone_number = models.IntegerField(blank=False, help_text='Contact phone number', null=True)
    nationality = models.CharField(max_length=155, blank=True)
    remarks = models.CharField(max_length=255, blank=True, null=True)
    traval_agent = models.CharField(max_length=255, blank=True)
    bill_setteled_by = models.CharField(max_length=255, blank=True)
    booked_by = models.CharField(max_length=255, blank=False)
    check_in = models.DateTimeField(auto_now=False, null=True)
    check_out = models.DateTimeField(auto_now=False, null=True, blank=True)
    main_id = models.ImageField(upload_to="customer/id", null=True, blank=True)

    def save(self, *args, **kwargs):
        if isinstance(self.check_in, str):
            self.check_in = nepali_datetime.date.from_str(self.check_in).to_datetime().date()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.full_name

    @property
    def total_room_cost(self):
        """Calculate the total cost of rooms booked by the customer."""
        total_cost = 0
        bookings = Booked.objects.filter(customer_details=self)
        for booking in bookings:
            for room in booking.room_id.all():
                total_days = (date.today() - self.check_in.date()).days
                total_cost += float(room.price_pernight) * total_days
        return total_cost

    @property
    def total_advance_payment(self):
        """Calculate the total advance payment made by the customer."""
        total_advance = Advance_payment.objects.filter(customer=self).aggregate(
            Sum('Advance_amount')
        )['Advance_amount__sum'] or 0
        return float(total_advance)

    @property
    def remaining_balance(self):
        """Calculate remaining balance, considering check-in and check-out dates."""
        if not self.check_in:
            return 0  # No check-in date means no balance calculation
        
        # Determine the effective end date for billing (today or check-out date)
        effective_end_date = min(date.today(), self.check_out.date()) if self.check_out else date.today()
        
        # Calculate the total number of days
        total_days = (effective_end_date - self.check_in.date()).days
        
        # Calculate the total room cost for the stay
        total_cost = self.total_room_cost * total_days
        
        # Calculate remaining balance
        return total_cost - self.total_advance_payment

class Additional_id(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    add_id = models.ImageField(upload_to="customer/add_id", null=True, blank=True)

class Grouped_room(models.Model):
    title = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.title

class Room(models.Model):
    room_status = (
        ("available", "available"),
        ("booked", "booked"),
        ("not-confirm", "confirm"),
        ("cancled", "cancled"),
        ("cleaning", "cleaning"),
        ("maintenance", "maintenance"),
    )
    room_number = models.CharField(max_length=255)
    group = models.ForeignKey(Grouped_room, on_delete=models.CASCADE, blank=True)
    price_pernight = models.CharField(max_length=255)
    status = models.CharField(max_length=255, choices=room_status, default="available")

    def __str__(self):
        return f"{self.room_number}"

class Booked(models.Model):
    customer_details = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    room_id = models.ManyToManyField(Room, blank=True)
    number_of_days = models.IntegerField(default=0, null=True, blank=True)
    booked_date = models.DateTimeField(auto_now_add=True, null=True)
    child = models.IntegerField(default=0, null=True, blank=True)
    male_number = models.IntegerField(default=0, null=True, blank=True)
    female_number = models.IntegerField(default=0, null=True, blank=True)
    other_gender = models.IntegerField(default=0, null=True, blank=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ["-booked_date"]

    @property
    def total_room(self):
        total_room = self.room_id.all()
        return total_room

    def __str__(self):
        return f'{self.customer_details}'

    @property
    def business_days(self):
        holidays = Customer.objects.values_list('check_in', flat=True)
        oneday = timedelta(days=1)
        dt = self.booked_date.date()
        total_days = 0
        while dt <= date.today():
            if not dt.isoweekday() in (6, 7) and dt not in holidays:
                total_days += 1
            dt += oneday
        return total_days

class Advance_payment(models.Model):
    Payment_mode = (
        ("Esewa", "Eswa"),
        ("Khalti", "Khalti"),
        ("Bank Transfer", "Bank Transfer"),
        ("Cash", "Cash"),
        ("Other", "Other"),
    )
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    Advance_amount = models.IntegerField()
    payment_day = models.DateTimeField(auto_now_add=True)
    payment_mode = models.CharField(max_length=255, choices=Payment_mode, default="available")
    remarks = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.customer.full_name

class Customer_list(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    checkin = models.DateTimeField(auto_now_add=True, null=True)
    checkout = models.CharField(max_length=255, default="stay")
    bookd_roooms = models.ForeignKey(Booked, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.customer.full_name

    @property
    def total_amount(self):
        total_amt = 0.0
        data = Advance_payment.objects.filter(customer=self.customer.id)
        for d in data:
            total_amt += float(d.Advance_amount)
        return total_amt

    @property
    def total_resturent_amount(self):
        res_total = 0.0
        query = Order.objects.filter(customer=self.customer).all()
        for q in query:
            res_total += float(q.total)
        return res_total

    @property
    def room_cost(self):
        res_total = 0.0
        query = self.bookd_roooms.room_id.all()
        for q in query:
            res_total += float(q.price_pernight)
        return res_total

    @property
    def all_rooms(self):
        return self.bookd_roooms.room_id.all()

class Ch_out(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    remaing_balance = models.FloatField(default=0, null=True)
    room_bill = models.FloatField(default=0, null=True)
    resturent_discount = models.FloatField(blank=True, null=True)
    vat = models.BooleanField(default=False)
    room_discount = models.FloatField(blank=True, null=True)
    remarks = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.customer.full_name

    @property
    def rem_bln(self):
        return self.remaing_balance or 0

    @property
    def resturent_dic(self):
        return self.resturent_discount or 0

    @property
    def room_dic(self):
        return self.room_discount or 0

class Order(models.Model):
    order_id = models.CharField(max_length=255, default=random_string_generator().upper(), unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, blank=True, null=True)
    total = models.CharField(max_length=255, null=True, blank=True)
    order_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.order_id}'

    @property
    def order_user(self):
        return f'{self.customer.full_name}'

class Non_room_user(models.Model):
    Payment_mode = (
        ("Esewa", "Eswa"),
        ("Khalti", "Khalti"),
        ("Bank Transfer", "Bank Transfer"),
        ("Cash", "Cash"),
        ("Other", "Other"),
    )
    order_id = models.CharField(max_length=255, default=random_string_generator().upper(), unique=True)
    full_name = models.CharField(max_length=255)
    phone_number = models.IntegerField()
    email = models.EmailField(blank=True, null=True)
    total = models.FloatField(max_length=255, null=True, blank=True)
    remaing_amount = models.FloatField(default=0)
    Payment_mode = models.CharField(max_length=255, choices=Payment_mode, null=True, default="UNPAID")
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.order_id} {self.full_name}'

templates/customer_detail.html
{% extends 'base.html' %}

templates/index.html
{% extends "base.html" %}

{% block content %}


            <div class="modal fade none-border" id="x_payment" >
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title"><strong>Pay Advance </strong></h4>
                        </div>
                        <div class="modal-body">
                            <div id="py-up">
                                <div class="text-center">
                                    <div class="spinner-border" role="status">
                                        <span class="sr-only">Loading...</span>
                                    </div>
                                </div>
                            </div>
                            <form id="payform">
            
                                {% csrf_token %}
            
                                <div class="row">
            
            
                                    {% for field in ad_form %}
                                    <div class="col-md-6">
            
                                        <label class="control-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                                        {{ field }}
                                    </div>
                                    {% endfor %}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" id="proced_pay"
                                        class="btn btn-danger waves-effect waves-light save-category" data-dismiss="modal">Proceed
                                        To Pay</button>
                                </div>
                            </form>
                        </div>
            
            
                    </div>
                </div>
            </div>
            <!-- Sale & Revenue Start -->
            <div class="container-fluid pt-4 px-4">

    <div class="row g-4">
        <!-- Check In -->
        <a href="{% url 'checkin' %}" class="col-sm-6 col-xl-3 btn">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fas fa-sign-in-alt fa-3x text-primary"></i>
                <div class="ms-3">
                    <h6 class="mb-0">Check In</h6>
                </div>
            </div>
        </a>

        <!-- Check Out -->

        <a href="{% url 'checkout' %}" class="col-sm-6 col-xl-3 btn">

            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fas fa-sign-out-alt fa-3x text-primary"></i>
                <div class="ms-3">
                    <h6 class="mb-0">Check Out</h6>
                </div>
            </div>
        </a>

        <!-- Room Manager -->
        <a href="{% url 'roommanager' %}" class="col-sm-6 col-xl-3 btn">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fas fa-bed fa-3x text-primary"></i>
                <div class="ms-3">
                    <h6 class="mb-0">Room Manager</h6>
                </div>
            </div>
        </a>

        <!-- Customer Details -->
        <a href="{% url 'report' %}" class="col-sm-6 col-xl-3 btn">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fas fa-file-alt fa-3x text-primary"></i>
                <div class="ms-3">
                    <h6 class="mb-0">Customer Details</h6>
                </div>
            </div>
        </a>
    </div>
</div>

<div class="container-fluid pt-4 px-4">
    <div class="bg-dark text-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Customer Status Management</h6>


            <p><strong>Total Cost of All Users:</strong> ${{ total_cost_all_users }}</p>
            <p><strong>Total Advance Given by Users:</strong> ${{ total_advance_all_users }}</p>
            <p><strong>Total Remaining Balance:</strong> ${{ total_remaining_balance_all_users }}</p>
            <form class="d-none d-md-flex ms-4">
                <input class="form-control bg-secondary text-light border-0" type="search" id="search" placeholder="Search">
            </form>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0 custom-table" id="customerTable">
                <thead class="table-light">
                    <tr role="row">
                        <th>Full Name</th>
                        <th>Check-in Date</th>
                        <th>Contact</th>
                        <th>Room Total</th>
                        <th>Advance</th>
                        <th>Remaining</th>
                        <th>Room Number</th>

                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>

                    {% for data in customer_data %}
                    <tr class="table-row">
                        <td>{{ data.customer.full_name }}</td>
                        <td>{{ data.customer.check_in }}</td>
                        <td>{{ data.customer.phone_number }}</td>
                        <td>{{ data.total_room_price }}</td>
                        <td>{{ data.total_advance }}</td>
                        <td>{{ data.remaining_balance }}</td>
                        <td>
                            {% for room in data.room_numbers %}
                                {{ room }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            <button type="button" class="btn btn-success btn-sm" onclick="ad_pay({{data.customer.id}})" id="ad_pay">

                                Pay Advance <i class="fas fa-money-bill-wave"></i>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Recent Customer Section -->

<div class="container-fluid pt-4 px-4">
    <div class="bg-dark text-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Recent Customer</h6>
            <a href="{% url 'report' %}" class="text-light">Show All</a>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0 custom-table">
                <thead class="table-dark">
                    <tr role="row">
                        <th>Full Name</th>
                        <th>Phone Number</th>
                        <th>Email</th>
                        <th>Location</th>
                        <th>IDs</th>
                        <th>Booked By</th>
                        <th>Checkin</th>
                        <th>Check Out</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cus in customer %}
                    <tr class="table-row">
                        <td>{{cus.full_name}}</td>
                        <td>{{cus.phone_number|upper}}</td>
                        <td>{{cus.email}}</td>
                        <td>{{cus.location|truncatechars:10}}</td>
                        <td>{{cus.passport_id_number}}</td>
                        <td>{{cus.booked_by}}</td>
                        <td>{{cus.check_in|date:"Y-m-d g:m A"}}</td>
                        <td>{{cus.check_out}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% block scripts %}
<script>
    document.getElementById('search').addEventListener('keyup', function () {
        var filter = this.value.toLowerCase();
        var rows = document.querySelectorAll('#customerTable tbody tr');
        
        rows.forEach(function(row) {
            var name = row.querySelector('td:first-child').textContent.toLowerCase();
            var contact = row.querySelector('td:nth-child(3)').textContent.toLowerCase();
            var roomTotal = row.querySelector('td:nth-child(4)').textContent.toLowerCase();
            var advance = row.querySelector('td:nth-child(5)').textContent.toLowerCase();
            var remaining = row.querySelector('td:nth-child(6)').textContent.toLowerCase();
            
            if (name.includes(filter) || contact.includes(filter) || roomTotal.includes(filter) || advance.includes(filter) || remaining.includes(filter)) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });

    function ad_pay(b) {
        $("#py-up").hide();
        $('#x_payment').modal('toggle');
        var user = b;

        let csr = $("input[name=csrfmiddlewaretoken]").val();

        $("#proced_pay").unbind("click").bind("click", function () {
            var amount = $("#id_Advance_amount").val();
            var paytype = $('#id_payment_type').find(':selected').val();
            var remarks = $('#id_remarks').val();
            var cred = {
                "user": user,
                "ammount": amount,
                "paytype": paytype,
                "remarks": remarks
            };
            $.ajax({
                method: 'POST',
                url: '{% url "checkout" %}',
                dataType: "json",
                headers: { "X-CSRFToken": csr },
                data: cred,
                beforesend: function () {
                    $("#py-up").show();
                },
                success: function (response) {
                    if (response.message == "success") {
                        $("#x_payment").modal('toggle');
                        $.notify("Payment has been made ", "success");
                    } else {
                        $.notify("Payments cant made !", "alert");
                    }
                },
                complete: function () {
                    $("#py-up").hide();
                }
            });
            $("#payform")[0].reset();
        });
    }
</script>
{% endblock scripts %}

{% endblock %}
